version: us
build_path: build/us
asm_path: asm/us
asset_path: assets/us
src_path: src
ld_script_path: build/us
generated_sym_path: build/us
align: 4
overlays:
  - name: main
    disk_path: disks/us/SCUS_941.63
    sha1: a95e8b16b97071203b953bb81a33980509262f30
    base_path: main
    symbol_addrs_path:
    - config/symbols.main.us.txt
    - config/sym_extern.us.txt
    migrate_rodata_to_functions: true
    vram_start: 0x80010000
    gp_value: 0x80062D44
    segments:
      - [0x800, .rodata, 110B8]
      - [0x938, .rodata, 14C70]
      - [0x958, .rodata, "17238"]
      - [0xA9C, .rodata, 1C0EC]
      - [0xAB4, .rodata, input]
      - [0xB00, .rodata, 1CDA4]
      - [0xB14, .rodata, 1F6B4]
      - [0xB60, .rodata, 26B70]
      - [0xB94, rodata, akao_rodata]
      - [0xC38, rodata, psxsdk_rodata]
      - [0x18B8, c, 110B8]
      - [0x4CD8, c, 144D8]
      - [0x50A0, c, btlinit]
      - [0x5354, c, btlrand]
      - [0x5470, c, 14C70]
      - [0x6344, c, 15B44]
      - [0x6514, c, unzip]
      - [0x7A38, c, "17238"]
      - [0xC8EC, c, 1C0EC]
      - [0xCC34, c, input]
      - [0xD5A4, c, 1CDA4]
      - [0xFEB4, c, 1F6B4]
      - [0x16C08, c, menutable]
      - [0x171C0, c, 269C0]
      - [0x1735C, c, 26B70]
      - [0x19BD0, c, akao]
      - [0x24370, c, psxsdk]
      - [0x394E0, data, psxsdk_card_data]
      - [0x394FC, data, 110B8]
      - [0x39584, data, 144D8]
      - [0x395F8, .data, unzip]
      - [0x39760, data, 48F60]
      - [0x39860, data, "17238"]
      - [0x39A08, data, 1CDA4]
      - [0x39A44, data, 1F6B4]
      - [0x39BA8, .data, ovl]
      - [0x39C50, data, 21D5C]
      - [0x39D38, data, akao]
      - [0x3AE34, data, psxsdk]
      - [0x5354C, .sdata, btlrand]
      - [0x53550, .sdata, 14C70]
      - [0x53554, .sdata, unzip]
      - [0x53560, .sdata, input]
      - [0x53578, .sdata, 1CDA4]
      - [0x535CC, .sdata, 1F6B4]
      - [0x535FC, .sdata, 26B70]
      - [0x53610, .sbss, btlrand]
      - [0x5361C, .sbss, 14C70]
      - [0x53630, .sbss, 15B44]
      - [0x53634, .sbss, unzip]
      - [0x53654, .sbss, "17238"]
      - [0x53694, .sbss, input]
      - [0x536A0, .sbss, 1F6B4]
      - [0x536D0, bss]
  - name: batini
    disk_path: disks/us/BATTLE/BATINI.X.dec
    sha1: 2771b06f7249d34ed8a4f8c94e6047f70278e17c
    base_path: battle
    symbol_addrs_path:
      - config/sym_export.us.txt
      - config/symbols.batini.txt
      - config/sym_export_battle.us.txt
    migrate_rodata_to_functions: true
    vram_start: 0x801B0000
    segments:
      - [0, .rodata, batini]
      - [0x50, c, batini]
  - name: batres
    disk_path: disks/us/BATTLE/BATRES.X.dec
    sha1: e7ae9182df1c8ee457bae5bf7d7dc63c61a8c3d8
    base_path: battle
    symbol_addrs_path:
      - config/sym_export.us.txt
      - config/symbols.batres.txt
      - config/sym_export_battle.us.txt
    migrate_rodata_to_functions: true
    vram_start: 0x801B0000
    bss_size: 0x4
    segments:
      - [0, c, batres]
  - name: battle
    disk_path: disks/us/BATTLE/BATTLE.X.dec
    sha1: c82690f814b18664c3b2d024f4edeea5743995d9
    base_path: battle
    symbol_addrs_path:
      - config/sym_export.us.txt
      - config/symbols.battle.txt
      - config/sym_battle_import.us.txt
    migrate_rodata_to_functions: true
    vram_start: 0x800A0000
    bss_size: 0x70684
    segments:
      - [0x0, .rodata, battle]
      - [0x5BC, .rodata, battle1]
      - [0x888, .rodata, battle2]
      - [0xDD4, .rodata, battle3]
      - [0x1158, c, battle]
      - [0x130E4, c, battle1]
      - [0x27B60, c, battle2]
      - [0x38A04, c, battle3]
      - [0x47A38, data]
      - [0x538AC, bss]
  - name: brom
    disk_path: disks/us/BATTLE/BROM.X.dec
    sha1: ebc7a6559f677d1caef8c5db5fd884fd9e0ab156
    base_path: brom
    symbol_addrs_path:
      - config/symbols.brom.us.txt
      - config/sym_export.us.txt
    migrate_rodata_to_functions: false
    vram_start: 0x800A0000
    segments:
      - [0x0, c, brom]
      - [0x6B4, data]
  - name: dschange
    disk_path: disks/us/FIELD/DSCHANGE.X
    sha1: e884441c5ceacdeb94e16a603b73ca53706078e8
    base_path: dschange
    symbol_addrs_path:
      - config/sym_export.us.txt
      - config/symbols.dschange.us.txt
    vram_start: 0x800A0000
    segments:
      - [0x0, c, dschange]
      - [0x1580, data]
      - [0x15E0, bss]
  - name: ending
    disk_path: disks/us/FIELD/ENDING.X
    sha1: 1b3fbf999913024209b23a1bb8a6874a66fc19ba
    base_path: ending
    symbol_addrs_path:
      - config/sym_export.us.txt
      - config/symbols.ending.us.txt
    vram_start: 0x800A0000
    segments:
      - [0x0, rodata]
      - [0x30, c, ending]
      - [0x3934, data]
      - [0x6524, bss]
  - name: field
    disk_path: disks/us/FIELD/FIELD.BIN.dec
    sha1: 9d4dc1688526f48a5e0706228e6a751d01871396
    base_path: field
    symbol_addrs_path:
      - config/sym_export.us.txt
      - config/symbols.field.us.txt
    migrate_rodata_to_functions: true
    vram_start: 0x800A0000
    segments:
      - [0x0, .rodata, field]
      - [0x1368, c, field]
      - [0x3A5B8, data]
  - name: bginmenu
    disk_path: disks/us/MENU/BGINMENU.MNU
    sha1: af17d71fa4738e53ec50df5d15d992a355500223
    base_path: menu
    symbol_addrs_path:
    - config/sym_export.us.txt
    - config/symbols.bginmenu.us.txt
    vram_start: 0x801D0000
    segments:
      - [0x0, c, bginmenu]
      - [0x7F0, data]
      - [0x860, bss]
  - name: cnfgmenu
    disk_path: disks/us/MENU/CNFGMENU.MNU
    sha1: 20450f6e53a204f0f3b251a3864f125bc7b27bb6
    base_path: menu
    symbol_addrs_path:
    - config/sym_export.us.txt
    - config/symbols.cnfgmenu.us.txt
    migrate_rodata_to_functions: true
    vram_start: 0x801D0000
    segments:
      - [0x0, .rodata, cnfgmenu]
      - [0x40, c, cnfgmenu]
      - [0x1AA8, .data, cnfgmenu]
      - [0x24CC, .bss, cnfgmenu]
  - name: savemenu
    disk_path: disks/us/MENU/SAVEMENU.MNU
    sha1: 430d54dbe01d9a0c670b1d2d2b5c642bdd1b3199
    base_path: menu
    symbol_addrs_path:
    - config/sym_export.us.txt
    - config/symbols.savemenu.us.txt
    migrate_rodata_to_functions: true
    vram_start: 0x801D0000
    segments:
      - [0x0, .rodata, savemenu]
      - [0x3B8, .rodata, title]
      - [0x408, c, savemenu]
      - [0x2B58, c, title]
      - [0x4EC4, data]
      - [0x12C78, .data, savemenu]
      - [0x13650, data]
      - [0x13698, bss]
  - name: itemmenu
    disk_path: disks/us/MENU/ITEMMENU.MNU
    sha1: baf50a4ab2d364d0a712b9f74ee69029db0b3b5c
    base_path: menu
    symbol_addrs_path:
    - config/sym_export.us.txt
    - config/symbols.itemmenu.us.txt
    migrate_rodata_to_functions: true
    vram_start: 0x801D0000
    segments:
      - [0x0, .rodata, itemmenu]
      - [0x1E8, c, itemmenu]
      - [0x3834, data, itemmenu]
      - [0x4020, bss]
  - name: world
    disk_path: disks/us/WORLD/WORLD.BIN.dec
    sha1: a6b26b066e6fb8b5985c928d76faeb6f5f29ce2c
    base_path: world
    symbol_addrs_path:
      - config/sym_export.us.txt
      - config/symbols.world.txt
    migrate_rodata_to_functions: true
    vram_start: 0x800A0000
    bss_size: 0x1D978
    segments:
      - [0x0, .rodata, world]
      - [0xB40, c, world]
      - [0x1D124, asm, world_unk]
      - [0x1FBF0, c, world2]
      - [0x265EC, data, world]
  - name: barrier
    disk_path: disks/us/MAGIC/BARRIER.BIN
    sha1: e93c458117a937879f1a6d8c956dfbdacd6286e0
    base_path: magic
    vram_start: 0x801B0000
    bss_size: 0x20008
    symbol_addrs_path:
      - config/sym_export.us.txt
      - config/symbols.magic-barrier.us.txt
      - config/sym_export_battle.us.txt
    segments:
      - [0, c, barrier]
      - [0xB68, .data, barrier]
      - [0xCC0, .bss, barrier]
  - name: brizad
    disk_path: disks/us/MAGIC/BRIZAD.BIN
    sha1: d06ef02a1e37a85eb6c0206c9793a44a713bfe82
    base_path: magic
    vram_start: 0x801B0000
    bss_size: 0x20004
    symbol_addrs_path:
      - config/sym_export.us.txt
      - config/symbols.magic-brizad.us.txt
      - config/sym_export_battle.us.txt
    segments:
      - [0, c, brizad]
      - [0x3f0, data, brizad]
      - [0x1014, .bss, brizad]
  - name: lv5deth
    disk_path: disks/us/MAGIC/LV5DETH.BIN
    sha1: 860f9495082983be362f605ca5da4968adf4c025
    base_path: magic
    vram_start: 0x801B0000
    symbol_addrs_path:
      - config/sym_export.us.txt
      - config/symbols.magic-lv5deth.us.txt
      - config/sym_export_battle.us.txt
    segments:
      - [0, c, lv5deth]
      - [0x5e0, data, lv5deth]
